// <auto-generated />
using System;
using LibraryManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementAPI.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20250122175455_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("author");

                    b.Property<uint>("CopiesInStock")
                        .HasColumnType("int unsigned")
                        .HasColumnName("copies_in_stock");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("language");

                    b.Property<string>("Overview")
                        .HasMaxLength(1800)
                        .HasColumnType("varchar(1800)")
                        .HasColumnName("overview");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<uint>("TotalCopies")
                        .HasColumnType("int unsigned")
                        .HasColumnName("total_copies");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("book", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Alan Brennert",
                            CopiesInStock = 0u,
                            Language = "English",
                            Overview = "An enlightening historical saga... Washington Post Hawaii, 1892. Rachel Kalama, a seven-year-old Hawaiian girl with a lively and mischievous spirit, dreams of visiting distant lands like her father, who serves in the merchant marine. Until one day, a pink spot appears on her skin, and her dreams of elsewhere vanish instantly. Taken from her home and family, Rachel is sent to Kalaupapa, a quarantine camp on the island of Moloka'i. It is there that her life is supposed to end – but she realizes that it is actually just beginning. Overflowing with warmth, humor, compassion, and a wonderfully portrayed cast of characters, this storytelling masterpiece speaks of a people who, in the face of the harsh reality of death, chose life.",
                            Title = "Moloka'i",
                            TotalCopies = 1u
                        },
                        new
                        {
                            Id = 2,
                            Author = "Sarah J. Maas",
                            CopiesInStock = 1u,
                            Language = "English",
                            Overview = "Feyre has undergone more trials than one human woman can carry in her heart. Though she's now been granted the powers and lifespan of the High Fae, she is haunted by her time Under the Mountain and the terrible deeds she performed to save the lives of Tamlin and his people.\n\nAs her marriage to Tamlin approaches, Feyre's hollowness and nightmares consume her. She finds herself split into two different people: one who upholds her bargain with Rhysand, High Lord of the feared Night Court, and one who lives out her life in the Spring Court with Tamlin. While Feyre navigates a dark web of politics, passion, and dazzling power, a greater evil looms. She might just be the key to stopping it, but only if she can harness her harrowing gifts, heal her fractured soul, and decide how she wishes to shape her future-and the future of a world in turmoil.\n\nBestselling author Sarah J. Maas's masterful storytelling brings this second book in her dazzling, sexy, action-packed series to new heights.",
                            Title = "A Court of Mist and Fury",
                            TotalCopies = 1u
                        },
                        new
                        {
                            Id = 5,
                            Author = "Harper Lee",
                            CopiesInStock = 4u,
                            Language = "English",
                            Overview = "A novel about the serious issues of rape and racial inequality told from the perspective of a young girl in the Deep South.",
                            Title = "To Kill a Mockingbird",
                            TotalCopies = 5u
                        },
                        new
                        {
                            Id = 6,
                            Author = "George Orwell",
                            CopiesInStock = 6u,
                            Language = "English",
                            Overview = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.",
                            Title = "1984",
                            TotalCopies = 8u
                        },
                        new
                        {
                            Id = 7,
                            Author = "Gabriel Garcia Marquez",
                            CopiesInStock = 7u,
                            Language = "Spanish",
                            Overview = "A multi-generational story that explores the magical and surreal experiences of the Buendía family.",
                            Title = "One Hundred Years of Solitude",
                            TotalCopies = 7u
                        },
                        new
                        {
                            Id = 8,
                            Author = "F. Scott Fitzgerald",
                            CopiesInStock = 3u,
                            Language = "English",
                            Overview = "A story about the young and mysterious millionaire Jay Gatsby and his quixotic passion for the beautiful Daisy Buchanan.",
                            Title = "The Great Gatsby",
                            TotalCopies = 3u
                        },
                        new
                        {
                            Id = 9,
                            Author = "Paulo Coelho",
                            CopiesInStock = 5u,
                            Language = "Portuguese",
                            Overview = "A philosophical book that tells the story of a young Andalusian shepherd on his journey to the pyramids of Egypt.",
                            Title = "The Alchemist",
                            TotalCopies = 4u
                        },
                        new
                        {
                            Id = 10,
                            Author = "Gary Goldschneider and Joost Elffers",
                            CopiesInStock = 4u,
                            Language = "English",
                            Overview = "Many have suspected that your birthday affects your personality and how you relate to others. Nineteen years and over one million copies later, The Secret Language of Birthdays continues to fascinate readers by describing the characteristics associated with being born on a particular day. And being born on a particular month describe one's personality..",
                            Title = "The Secret Language of Birthdays",
                            TotalCopies = 4u
                        },
                        new
                        {
                            Id = 12,
                            Author = "Arthur Conan Doyle",
                            CopiesInStock = 6u,
                            Language = "English, Finnish, German, Spanish, Polish",
                            Overview = "The Hound of the Baskervilles is the third of the four crime novels by British writer Arthur Conan Doyle featuring the detective Sherlock Holmes. Originally serialised in The Strand Magazine from August 1901 to April 1902, it is set in 1889 largely on Dartmoor in Devon in England's West Country and tells the story of an attempted murder inspired by the legend of a fearsome, diabolical hound of supernatural origin. Holmes and Watson investigate the case. This was the first appearance of Holmes since his apparent death in \"The Final Problem\", and the success of The Hound of the Baskervilles led to the character's eventual revival.\nOne of the most famous stories ever written, in 2003, the book was listed as number 128 of 200 on the BBC's The Big Read poll of the UK's \"best-loved novel\". In 1999, a poll of \"Sherlockians\" ranked it as the best of the four Holmes novels.",
                            Title = "The Hound of the Baskervilles",
                            TotalCopies = 6u
                        },
                        new
                        {
                            Id = 23,
                            Author = "Test",
                            CopiesInStock = 0u,
                            Language = "Eng",
                            Overview = "dd",
                            Title = "Test Book",
                            TotalCopies = 1u
                        },
                        new
                        {
                            Id = 24,
                            Author = "Francis Ledwidge",
                            CopiesInStock = 5u,
                            Language = "English",
                            Overview = "",
                            Title = "The complete poems of Francis Ledwidge",
                            TotalCopies = 6u
                        });
                });

            modelBuilder.Entity("LibraryManagementAPI.Models.Borrower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("borrower", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            Telephone = "(555) 123-4567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "alex.johnson@example.com",
                            FullName = "Alex Johnson",
                            Telephone = "+1-555-123-4567"
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria.garcia@example.com",
                            FullName = "Maria Garcia",
                            Telephone = "+1-555-987-6543"
                        },
                        new
                        {
                            Id = 4,
                            Email = "liam.smith@example.com",
                            FullName = "Liam Smith",
                            Telephone = "+1-555-246-8101"
                        },
                        new
                        {
                            Id = 5,
                            Email = "emma.brown@example.com",
                            FullName = "Emma Brown",
                            Telephone = "+1-555-135-7913"
                        },
                        new
                        {
                            Id = 6,
                            Email = "noah.wilson@example.com",
                            FullName = "Noah Wilson",
                            Telephone = "+1-555-321-0987"
                        },
                        new
                        {
                            Id = 7,
                            Email = "olivia.davis@example.com",
                            FullName = "Olivia Davis",
                            Telephone = "+1-555-654-3210"
                        },
                        new
                        {
                            Id = 8,
                            Email = "william.taylor@example.com",
                            FullName = "William Taylor",
                            Telephone = "+1-555-789-0123"
                        },
                        new
                        {
                            Id = 9,
                            Email = "ava.martinez@example.com",
                            FullName = "Ava Martinez",
                            Telephone = "+1-555-876-5432"
                        },
                        new
                        {
                            Id = 10,
                            Email = "james.anderson@example.com",
                            FullName = "James Anderson",
                            Telephone = "+1-555-234-5678"
                        },
                        new
                        {
                            Id = 11,
                            Email = "sophia.thomas@example.com",
                            FullName = "Sophia Thomas",
                            Telephone = "+1-555-567-8901"
                        });
                });

            modelBuilder.Entity("LibraryManagementAPI.Models.IssuedBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int")
                        .HasColumnName("borrower_id");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<int>("LibrarianId")
                        .HasColumnType("int")
                        .HasColumnName("librarian_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("ReturnBefore")
                        .HasColumnType("date")
                        .HasColumnName("return_before");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookId" }, "book_id");

                    b.HasIndex(new[] { "BorrowerId" }, "borrower_id");

                    b.HasIndex(new[] { "LibrarianId" }, "librarian_id");

                    b.ToTable("issued_book", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10,
                            BookId = 1,
                            BorrowerId = 10,
                            IssueDate = new DateOnly(2024, 8, 15),
                            LibrarianId = 16,
                            Notes = "First issued book",
                            ReturnBefore = new DateOnly(2024, 9, 8)
                        },
                        new
                        {
                            Id = 12,
                            BookId = 6,
                            BorrowerId = 3,
                            IssueDate = new DateOnly(2024, 8, 19),
                            LibrarianId = 16,
                            Notes = "Second issued book",
                            ReturnBefore = new DateOnly(2024, 9, 7)
                        },
                        new
                        {
                            Id = 13,
                            BookId = 6,
                            BorrowerId = 4,
                            IssueDate = new DateOnly(2024, 8, 19),
                            LibrarianId = 16,
                            Notes = "Third issued book",
                            ReturnBefore = new DateOnly(2024, 8, 22)
                        },
                        new
                        {
                            Id = 14,
                            BookId = 5,
                            BorrowerId = 9,
                            IssueDate = new DateOnly(2024, 8, 15),
                            LibrarianId = 16,
                            Notes = "Fourth issued book",
                            ReturnBefore = new DateOnly(2024, 8, 27)
                        },
                        new
                        {
                            Id = 15,
                            BookId = 24,
                            BorrowerId = 6,
                            IssueDate = new DateOnly(2024, 8, 16),
                            LibrarianId = 16,
                            Notes = "Fifth issued book",
                            ReturnBefore = new DateOnly(2024, 8, 23)
                        });
                });

            modelBuilder.Entity("LibraryManagementAPI.Models.Librarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("librarian", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 16,
                            FirstName = "Test",
                            LastName = "User",
                            Login = "librarian_test_user",
                            Password = "AQAAAAIAAYagAAAAEIDBJ989IN736ilY0FayybfTiIAxknayxo2MGhwVLtdH1yLAIY32SGOwoVNvLmLduA=="
                        });
                });

            modelBuilder.Entity("LibraryManagementAPI.Models.IssuedBook", b =>
                {
                    b.HasOne("LibraryManagementAPI.Models.Book", "Book")
                        .WithMany("IssuedBooks")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("issued_book_ibfk_1");

                    b.HasOne("LibraryManagementAPI.Models.Borrower", "Borrower")
                        .WithMany("IssuedBooks")
                        .HasForeignKey("BorrowerId")
                        .IsRequired()
                        .HasConstraintName("issued_book_ibfk_2");

                    b.HasOne("LibraryManagementAPI.Models.Librarian", "Librarian")
                        .WithMany("IssuedBooks")
                        .HasForeignKey("LibrarianId")
                        .IsRequired()
                        .HasConstraintName("issued_book_ibfk_3");

                    b.Navigation("Book");

                    b.Navigation("Borrower");

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("LibraryManagementAPI.Models.Book", b =>
                {
                    b.Navigation("IssuedBooks");
                });

            modelBuilder.Entity("LibraryManagementAPI.Models.Borrower", b =>
                {
                    b.Navigation("IssuedBooks");
                });

            modelBuilder.Entity("LibraryManagementAPI.Models.Librarian", b =>
                {
                    b.Navigation("IssuedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
